name: Generate Lighthouse audit

on:
  deployment:
  schedule:
    - cron: '0 0 * * 0' # Every week (on Sunday, 00:00)
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Checkout dependent repository for badge generation
        uses: actions/checkout@v4
        with:
          repository: 'myactionway/lighthouse-badges'
          path: temp_lighthouse_badges_nested

      - name: Perform Lighthouse audit
        uses: myactionway/lighthouse-badger-action@v2.2
        with:
          urls: https://jortvanleenen.nl
          badges_args: '-b pagespeed -o .github/lighthouse-audit-results'
          mobile_lighthouse_params: '--form-factor=mobile --screenEmulation.mobile --screenEmulation.width=360 --screenEmulation.height=640 --screenEmulation.deviceScaleFactor=2 --throttling.cpuSlowdownMultiplier=2'
          desktop_lighthouse_params: '--preset=desktop'
          user_name: jortvanleenen
          user_email: jortvanleenen@users.noreply.github.com
          commit_message: Update Lighthouse audit SVGs
